server.port=${PORT:8080}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
# Ruta donde Spring Boot buscará las vistas Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/

# Extensión de los archivos de vista
spring.thymeleaf.suffix=.html

# Conexión a MongoDB
spring.data.mongodb.uri=mongodb+srv://pepito:pepitoclavounclavito@cluster0.cxavrrm.mongodb.net/Prueba?retryWrites=true&w=majority

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
