# Ruta donde Spring Boot buscar� las vistas Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/

# Extensi�n de los archivos de vista
spring.thymeleaf.suffix=.html

# Conexi�n a MongoDB
spring.data.mongodb.uri=mongodb+srv://pepito:pepitoclavounclavito@cluster0.cxavrrm.mongodb.net/Prueba?retryWrites=true&w=majority

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true